- name: tomcat
  hosts: application_app
  become: true
  vars:
    - TOMCAT9_URL : "https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.19/bin/apache-tomcat-10.1.19.tar.gz"
  
  tasks:
  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600 
  
  - name: Download Tomcat
    get_url:
      url: "{{ TOMCAT9_URL }}"
      dest: /tmp/
      validate_certs: no
      
  - name: Creating Apache Tomcat home directory.
    command: mkdir /opt/tomcat  
      
  - name: Extract Tomcat
    shell: tar -xzvf /tmp/apache-tomcat-10.1.19.tar.gz -C /opt/tomcat --strip-components=1
  
  - name: Start Tomcat
    shell: /opt/tomcat/bin/startup.sh
    ignore_errors: true
  
  - name: Wait for Tomcat to start
    wait_for:
      host: localhost
      port: 8080
      state: started